export const PREDEFINED_LISTS = {
  animals: [
    "Elephant",
    "Lion",
    "Giraffe",
    "Tiger",
    "Dolphin",
    "Eagle",
    "Koala",
    "Penguin",
    "Zebra",
  ],
  fruits: [
    "Apple",
    "Banana",
    "Orange",
    "Strawberry",
    "Pineapple",
    "Mango",
    "Watermelon",
    "Grape",
    "Kiwi",
  ],
  objects: [
    "Lamp",
    "Phone",
    "Watch",
    "Book",
    "Key",
    "Chair",
    "Pen",
    "Cup",
    "Glasses",
  ],
};
// export const wordsArray = [
//   // Frutas
//   "apple",
//   "banana",
//   "grape",
//   "orange",
//   "watermelon",
//   "strawberry",
//   "cherry",
//   "lemon",
//   "peach",
//   "plum",
//   "pineapple",
//   "kiwi",
//   "mango",
//   "blueberry",
//   "raspberry",
//   "blackberry",
//   "melon",
//   "papaya",
//   "coconut",
//   "pear",
//   "apricot",
//   "fig",
//   "lime",
//   "pomegranate",
//   "date",
//   "persimmon",
//   "quince",
//   "grapefruit",
//   "cranberry",
//   "nectarine",

//   // Lugares
//   "airport",
//   "beach",
//   "park",
//   "library",
//   "restaurant",
//   "museum",
//   "cafe",
//   "mall",
//   "hospital",
//   "school",
//   "university",
//   "gym",
//   "hotel",
//   "theater",
//   "stadium",
//   "zoo",
//   "station",
//   "bus stop",
//   "amusement park",
//   "aquarium",
//   "bakery",
//   "church",
//   "post office",
//   "market",
//   "bank",
//   "pharmacy",
//   "cinema",
//   "bridge",
//   "river",
//   "mountain",

//   // Animales
//   "dog",
//   "cat",
//   "lion",
//   "tiger",
//   "elephant",
//   "giraffe",
//   "monkey",
//   "zebra",
//   "bear",
//   "wolf",
//   "rabbit",
//   "fox",
//   "deer",
//   "horse",
//   "sheep",
//   "goat",
//   "cow",
//   "chicken",
//   "duck",
//   "eagle",
//   "penguin",
//   "dolphin",
//   "whale",
//   "shark",
//   "octopus",
//   "frog",
//   "kangaroo",
//   "koala",
//   "panda",
//   "bat",

//   // Elementos de uso diario
//   "phone",
//   "laptop",
//   "toothbrush",
//   "comb",
//   "wallet",
//   "keys",
//   "umbrella",
//   "backpack",
//   "pen",
//   "notebook",
//   "water bottle",
//   "glasses",
//   "charger",
//   "towel",
//   "shampoo",
//   "soap",
//   "sponge",
//   "remote",
//   "pillow",
//   "blanket",
//   "headphones",
//   "scissors",
//   "mask",
//   "sunscreen",
//   "mirror",
//   "watch",
//   "calendar",
//   "lamp",
//   "bottle opener",
//   "toaster",

//   // Elementos de vestimenta
//   "shirt",
//   "pants",
//   "jeans",
//   "sweater",
//   "jacket",
//   "coat",
//   "dress",
//   "skirt",
//   "blouse",
//   "t-shirt",
//   "shorts",
//   "socks",
//   "scarf",
//   "hat",
//   "gloves",
//   "belt",
//   "tie",
//   "shoes",
//   "sandals",
//   "boots",
//   "sneakers",
//   "umbrella",
//   "sunglasses",
//   "watch",
//   "ring",
//   "bracelet",
//   "necklace",
//   "earrings",
//   "cap",
//   "hoodie",
// ];
