export const PREDEFINED_LISTS = {
  animals: [
    "dog",
    "cat",
    "lion",
    "tiger",
    "elephant",
    "bear",
    "panda",
    "giraffe",
    "zebra",
    "monkey",
    "chimpanzee",
    "gorilla",
    "orangutan",
    "lemur",
    "koala",
    "kangaroo",
    "platypus",
    "wombat",
    "otter",
    "beaver",
    "fox",
    "wolf",
    "coyote",
    "deer",
    "elk",
    "moose",
    "bison",
    "buffalo",
    "rabbit",
    "hare",
    "squirrel",
    "hamster",
    "guinea pig",
    "chinchilla",
    "porcupine",
    "hedgehog",
    "mole",
    "bat",
    "raccoon",
    "skunk",
    "seal",
    "sea lion",
    "walrus",
    "dolphin",
    "whale",
    "shark",
    "octopus",
    "squid",
    "crab",
    "lobster",
    "shrimp",
    "jellyfish",
    "starfish",
    "turtle",
    "tortoise",
    "alligator",
    "crocodile",
    "snake",
    "lizard",
    "iguana",
    "frog",
    "toad",
    "salamander",
    "newt",
    "chameleon",
    "crow",
    "raven",
    "canary",
    "parrot",
    "eagle",
    "hawk",
    "owl",
    "falcon",
    "penguin",
    "flamingo",
    "pelican",
    "dove",
    "robin",
    "cardinal",
    "blue jay",
    "sparrow",
    "finch",
    "swallow",
    "goose",
    "duck",
    "chicken",
    "turkey",
    "pig",
    "cow",
    "horse",
    "sheep",
    "goat",
    "camel",
    "llama",
    "alpaca",
    "yak",
    "donkey",
    "mule",
    "hippopotamus",
    "rhinoceros"
  ],
  groceries: [
    "apples",
    "bananas",
    "oranges",
    "strawberries",
    "grapes",
    "blueberries",
    "lemons",
    "limes",
    "avocados",
    "tomatoes",
    "onions",
    "garlic",
    "carrots",
    "spinach",
    "lettuce",
    "kale",
    "broccoli",
    "cauliflower",
    "cucumbers",
    "bell peppers",
    "mushrooms",
    "potatoes",
    "sweet potatoes",
    "corn",
    "peas",
    "zucchini",
    "celery",
    "cilantro",
    "parsley",
    "ginger",
    "jalapenos",
    "yogurt",
    "milk",
    "butter",
    "cheddar cheese",
    "mozzarella cheese",
    "cream cheese",
    "eggs",
    "chicken breast",
    "ground beef",
    "salmon",
    "shrimp",
    "pork chops",
    "bacon",
    "sausage",
    "bread",
    "tortillas",
    "bagels",
    "croissants",
    "rice",
    "pasta",
    "oats",
    "flour",
    "sugar",
    "brown sugar",
    "honey",
    "maple syrup",
    "olive oil",
    "vegetable oil",
    "salt",
    "black pepper",
    "garlic powder",
    "onion powder",
    "paprika",
    "cumin",
    "chili powder",
    "oregano",
    "basil",
    "thyme",
    "rosemary",
    "curry powder",
    "turmeric",
    "cinnamon",
    "nutmeg",
    "vanilla extract",
    "canned tomatoes",
    "tomato sauce",
    "tuna",
    "black beans",
    "chickpeas",
    "kidney beans",
    "corn (canned)",
    "coconut milk",
    "olives",
    "pickles",
    "salsa",
    "crackers",
    "pretzels",
    "popcorn",
    "chocolate",
    "chips",
    "granola bars",
    "almonds",
    "walnuts",
    "cashews",
    "peanut butter",
    "almond butter",
    "soy sauce",
    "balsamic vinegar",
    "chicken stock",
  ],
  objects: [
    "umbrella",
    "suitcase",
    "toothbrush",
    "mug",
    "laptop",
    "headphones",
    "coffee maker",
    "blender",
    "flashlight",
    "screwdriver",
    "hammer",
    "wrench",
    "measuring tape",
    "ladder",
    "broom",
    "vacuum cleaner",
    "kettle",
    "frying pan",
    "spatula",
    "cutting board",
    "plate",
    "glass",
    "napkin",
    "blanket",
    "pillow",
    "t-shirt",
    "jeans",
    "sweater",
    "socks",
    "shoes",
    "hat",
    "scarf",
    "sunglasses",
    "watch",
    "ring",
    "necklace",
    "smartphone",
    "charger",
    "camera",
    "tripod",
    "printer",
    "desk",
    "chair",
    "bookshelf",
    "lamp",
    "clock",
    "rug",
    "curtain",
    "pillowcase",
    "towel",
    "soap",
    "shampoo",
    "toothpaste",
    "conditioner",
    "calendar",
    "stapler",
    "paper clips",
    "notebook",
    "pen",
    "pencil",
    "eraser",
    "textbook",
    "ruler",
    "compass",
    "glue",
    "tape",
    "scissors",
    "glue gun",
    "corkscrew",
    "bottle opener",
    "can opener",
    "spoon",
    "ladle",
    "dish rack",
    "dish soap",
    "sponge",
    "dish towel",
    "microwave",
    "oven mitts",
    "baking sheet",
    "roasting pan",
    "pot",
    "colander",
    "measuring cup",
    "mixing bowl",
    "whisk",
    "pepper grinder",
    "salt shaker",
    "pepper mill",
    "sugar bowl",
    "milk jug",
    "butter dish",
    "cheese grater",
    "cutting mat",
    "wireless mouse",
    "external hard drive",
    "USB flash drive",
    "printer paper",
    "USB-C hub",
    "power strip",
  ],
};
// export const wordsArray = [
//   // Frutas
//   "apple",
//   "banana",
//   "grape",
//   "orange",
//   "watermelon",
//   "strawberry",
//   "cherry",
//   "lemon",
//   "peach",
//   "plum",
//   "pineapple",
//   "kiwi",
//   "mango",
//   "blueberry",
//   "raspberry",
//   "blackberry",
//   "melon",
//   "papaya",
//   "coconut",
//   "pear",
//   "apricot",
//   "fig",
//   "lime",
//   "pomegranate",
//   "date",
//   "persimmon",
//   "quince",
//   "grapefruit",
//   "cranberry",
//   "nectarine",

//   // Lugares
//   "airport",
//   "beach",
//   "park",
//   "library",
//   "restaurant",
//   "museum",
//   "cafe",
//   "mall",
//   "hospital",
//   "school",
//   "university",
//   "gym",
//   "hotel",
//   "theater",
//   "stadium",
//   "zoo",
//   "station",
//   "bus stop",
//   "amusement park",
//   "aquarium",
//   "bakery",
//   "church",
//   "post office",
//   "market",
//   "bank",
//   "pharmacy",
//   "cinema",
//   "bridge",
//   "river",
//   "mountain",

//   // Animales
//   "dog",
//   "cat",
//   "lion",
//   "tiger",
//   "elephant",
//   "giraffe",
//   "monkey",
//   "zebra",
//   "bear",
//   "wolf",
//   "rabbit",
//   "fox",
//   "deer",
//   "horse",
//   "sheep",
//   "goat",
//   "cow",
//   "chicken",
//   "duck",
//   "eagle",
//   "penguin",
//   "dolphin",
//   "whale",
//   "shark",
//   "octopus",
//   "frog",
//   "kangaroo",
//   "koala",
//   "panda",
//   "bat",

//   // Elementos de uso diario
//   "phone",
//   "laptop",
//   "toothbrush",
//   "comb",
//   "wallet",
//   "keys",
//   "umbrella",
//   "backpack",
//   "pen",
//   "notebook",
//   "water bottle",
//   "glasses",
//   "charger",
//   "towel",
//   "shampoo",
//   "soap",
//   "sponge",
//   "remote",
//   "pillow",
//   "blanket",
//   "headphones",
//   "scissors",
//   "mask",
//   "sunscreen",
//   "mirror",
//   "watch",
//   "calendar",
//   "lamp",
//   "bottle opener",
//   "toaster",

//   // Elementos de vestimenta
//   "shirt",
//   "pants",
//   "jeans",
//   "sweater",
//   "jacket",
//   "coat",
//   "dress",
//   "skirt",
//   "blouse",
//   "t-shirt",
//   "shorts",
//   "socks",
//   "scarf",
//   "hat",
//   "gloves",
//   "belt",
//   "tie",
//   "shoes",
//   "sandals",
//   "boots",
//   "sneakers",
//   "umbrella",
//   "sunglasses",
//   "watch",
//   "ring",
//   "bracelet",
//   "necklace",
//   "earrings",
//   "cap",
//   "hoodie",
// ];
